version: '3.8'

services:
  streamlit:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    depends_on:
      - fastapi
      - postgres

  fastapi:
    build: .
    command: uvicorn utils.api:fastapi_app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: user_dsa7
      POSTGRES_PASSWORD: user_dsa7
      POSTGRES_DB: yolo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
